### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by dmetacarpa24** [stat231-f21/blog_los-hermanos-intermareales#1]
### Los Hermanos Intermareales
___
**Deadlines**
_11/2 (10pm)_: Blog Proposal
_11/9 (10pm)_: Data Wrangling Completed
- We plan to add more data sets to the data that we have already used, but the new data is unwrangled, and we will need to continue wrangling data and combining it into one complete dataset for our blog

_11/12_: Incorporation of new data into existing visualizations complete
_11/16 (10pm)_: Have the first versions of all of our visualizations complete
- We can edit and change our visualizations after if we please, but we should at least have a few visualizations and working blog by the 16th

_11/19_: All Spatial Data Visualizations and Google Earth Function are Fully Running
_11/26_: Finishing Touches and Themes Complete
_11/30 (beginning of class)_: Presentation
_12/9 (5pm)_: Final Blog Due
_12/10 (5pm)_: Peer Group Reflection Due

**Blog**
_Proposal_:
	We plan to continue adding to the shiny app that we created earlier on in the semester. We will edit and add onto the visualizations that we already had in order to enhance them and incorporate new data and interactive widgets. Data collected in 2014 will be added to the dataset that we have been using so that users can now compare data from 2020 to data from 2014, and we will add data and columns to the dataset so that we will have more versatile data to work with. We will also include spatial data visualizations that show the locations of where the data was collected on leaflet maps, and we will construct a hull map visualization that shows the relationships between beaches and an NMD plot that shows how similar beaches are through distance between data points on the plot. We may also include a jaccard similarity index of the data collection sites. In addition, we will try to incorporate a visualization that allows users to see the beachfront views through google earth. Pictures of the beaches where the data was collected will also be included in the blog for aesthetics, and our blog will include a published shiny application.

**Comment by dmetacarpa24** [comment]
**Status Update 1 (November 9)**

We currently have all of the new data that we want to include wrangled, and we have also begun writing the code and text chunks for our actual blog. We included more data from 2014 and additional nutrients data. We also incorporated data about the lat/long coordinates of the beaches. We began writing the preliminary drafts of the introduction and discussion of the questions that we want to ask. We figured out how to work with Google Earth in R Markdown files, and we have almost figured out how to include Google Earth photo spheres in our blog. We also began updating our visualizations with our new data, and we generated some enhanced visualizations to explore our data in greater depth. We are on track with our plan, and hope to complete the remaining visualizations within the next few days.

**Comment by ctilton23** [comment]
Status Update 2 (11/16)
	So far, we have completed all of the data wrangling and incorporated five data visualizations into our blog. We are thinking about adding one or two more but are working on cleaning those tables up first. We are also in the process of completing our spatial data visualization. We were able to create a visualization that maps out the locations of all of the beaches where our data was collected, but we have not embedded it into the blog yet. We do not expect this will pose any challenges though since we already have the map running. We have completed the first draft of our introduction, and we are continuing to write all of the analysis for our visualizations. We are in a good spot leading into break, and hopefully, we will have the first draft of all of our blog components completed by Thursday (11/18). This would include having all visualizations embedded in the blog and first drafts of our analysis written. However, we have diverted a bit from our original plan when it comes to the shiny app. At first, we thought it would be a good idea to incorporate our old shiny app into the blog, but as we have progressed through the project, we realised that it would be more aesthetically pleasing and user friendly if we divided the visualizations between tabs on our blog. This would be instead of having a tab that leads to an app with more tabs. We do hope to include a smaller version of our app in order to incorporate interactive widgets into the blog.

**Comment by bebailey** [comment]
Just had a peek at your blog. Looking good! 

If you decide to incorporate the Shiny app, you will need to publish it to shinyapps.io and then embed the app using a code chunk (see [this link](https://bookdown.org/yihui/bookdown/web-pages-and-shiny-apps.html) for details):

```
knitr::include_app("https://your-account.shinyapps.io/your-app/", height = "600px")
```

I know you are still working on things and may already have plans to update this, but just a quick heads up that you might consider resizing many of your figures (e.g., the nutrient levels figure could be wider, the MDS scatterplot could be shorter). [Aesthetically pleasing graphical design](https://academics.skidmore.edu/blogs/ah108-18spring/files/2018/01/Tufte-Visual-Display-of-Quantative-Information.pdf) favors the horizontal—in other words, within a plot you want to aim for having the *x* axis about 1.5 times the length of the *y* axis (the "Golden rectangle" is a length:width ratio of 1.618:1). I'll be posting something on Campuswire about this soon...
